import type { Recipe } from '../../types';

/**
 * Emirati and wider Gulf recipes. All quantities are per ONE serving; the
 * planner multiplies them to hit your macro targets, so base amounts sit at a
 * normal portion — roughly 400-700 kcal for mains, 150-350 kcal for snacks.
 *
 * `fixed: true` marks aromatics and seasonings that should not grow with the
 * portion. Nobody wants 1.8x the baharat because they are bulking.
 *
 * These are dishes you can actually buy the parts for at Union Coop and Lulu,
 * rewritten around gram-accurate macros — not the Swedish pool with the names
 * changed. Where a classic does not survive the rewrite honestly it is left out
 * rather than faked: balaleet needs vermicelli nobody stocks here, dried lime
 * (loomi) and coconut milk are not on the shelf either, so kabsa, machboos and
 * the prawn masala lean on lemon, baharat and tomato instead of the versions
 * that would call for them.
 *
 * `name` and `en` hold the same string, and `stepsLocal` repeats `steps`. The
 * region's own language is English, so there is no second version to write and
 * inventing one would be worse than repeating it.
 */
export const AE_RECIPES: Recipe[] = [
  // ── Breakfast ────────────────────────────────────────────────────────────
  {
    id: 'ae-shakshuka-feta',
    name: 'Shakshuka with feta',
    en: 'Shakshuka with feta',
    slots: ['breakfast', 'lunch'],
    minutes: 20,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-eggs', g: 120 },
      { id: 'ae-tomato', g: 200 },
      { id: 'ae-bell-pepper', g: 80 },
      { id: 'ae-onion', g: 60, fixed: true },
      { id: 'ae-feta', g: 30 },
      { id: 'ae-olive-oil', g: 10, fixed: true },
      { id: 'ae-cumin', g: 2, fixed: true },
    ],
    steps: [
      'Soften the onion and pepper in the oil over a medium heat, about six minutes.',
      'Add the chopped tomato and cumin and simmer until thick, about eight minutes.',
      'Make two wells, crack in the eggs, cover and cook until the whites set.',
      'Crumble the feta over the top.',
    ],
    stepsLocal: [
      'Soften the onion and pepper in the oil over a medium heat, about six minutes.',
      'Add the chopped tomato and cumin and simmer until thick, about eight minutes.',
      'Make two wells, crack in the eggs, cover and cook until the whites set.',
      'Crumble the feta over the top.',
    ],
  },
  {
    id: 'ae-foul-medames',
    name: 'Foul medames',
    en: 'Foul medames',
    slots: ['breakfast'],
    minutes: 15,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-fava-beans', g: 240 },
      { id: 'ae-tomato', g: 100 },
      { id: 'ae-cucumber', g: 100 },
      { id: 'ae-onion', g: 30, fixed: true },
      { id: 'ae-garlic', g: 5, fixed: true },
      { id: 'ae-lemon', g: 10, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
      { id: 'ae-cumin', g: 2, fixed: true },
    ],
    steps: [
      'Warm the fava beans with their liquid, the crushed garlic and cumin for five minutes.',
      'Mash roughly with a fork, leaving some beans whole.',
      'Finish with the oil and lemon, and serve with the chopped tomato and cucumber alongside.',
    ],
    stepsLocal: [
      'Warm the fava beans with their liquid, the crushed garlic and cumin for five minutes.',
      'Mash roughly with a fork, leaving some beans whole.',
      'Finish with the oil and lemon, and serve with the chopped tomato and cucumber alongside.',
    ],
  },
  {
    id: 'ae-labneh-zaatar-flatbread',
    name: "Labneh with za'atar and flatbread",
    en: "Labneh with za'atar and flatbread",
    slots: ['breakfast'],
    minutes: 5,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-labneh', g: 200 },
      { id: 'ae-flatbread', g: 70 },
      { id: 'ae-cucumber', g: 80 },
      { id: 'ae-tomato', g: 80 },
      { id: 'ae-zaatar', g: 6, fixed: true },
      { id: 'ae-olive-oil', g: 8, fixed: true },
    ],
    steps: [
      'Spread the labneh on a plate, dimple it with a spoon and pour the oil into the dimples.',
      "Scatter the za'atar over the top.",
      'Warm the flatbread and serve with the sliced cucumber and tomato.',
    ],
    stepsLocal: [
      'Spread the labneh on a plate, dimple it with a spoon and pour the oil into the dimples.',
      "Scatter the za'atar over the top.",
      'Warm the flatbread and serve with the sliced cucumber and tomato.',
    ],
  },
  {
    id: 'ae-chickpea-egg-hash',
    name: 'Chickpea and egg hash',
    en: 'Chickpea and egg hash',
    slots: ['breakfast'],
    minutes: 15,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-eggs', g: 120 },
      { id: 'ae-chickpeas-tinned', g: 200 },
      { id: 'ae-bell-pepper', g: 80 },
      { id: 'ae-onion', g: 50, fixed: true },
      { id: 'ae-tomato', g: 80 },
      { id: 'ae-olive-oil', g: 8, fixed: true },
      { id: 'ae-cumin', g: 2, fixed: true },
      { id: 'ae-spices', g: 1, fixed: true },
    ],
    steps: [
      'Soften the onion and pepper in the oil, then add the drained chickpeas and let them catch a little.',
      'Add the tomato, cumin and spices and cook five minutes until it thickens.',
      'Make wells, crack in the eggs and cover until the whites set.',
    ],
    stepsLocal: [
      'Soften the onion and pepper in the oil, then add the drained chickpeas and let them catch a little.',
      'Add the tomato, cumin and spices and cook five minutes until it thickens.',
      'Make wells, crack in the eggs and cover until the whites set.',
    ],
  },
  {
    id: 'ae-date-tahini-overnight-oats',
    name: 'Date and tahini overnight oats',
    en: 'Date and tahini overnight oats',
    slots: ['breakfast'],
    minutes: 5,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-oats', g: 70 },
      { id: 'ae-milk', g: 200 },
      { id: 'ae-dates', g: 30 },
      { id: 'ae-tahini', g: 15, fixed: true },
      { id: 'ae-chia-seeds', g: 10 },
      { id: 'ae-honey', g: 8, fixed: true },
    ],
    steps: [
      'Stir the oats, milk, tahini, chia and chopped dates together in a jar.',
      'Drizzle over the honey.',
      'Refrigerate overnight. Keeps three days, so make the batch at once.',
    ],
    stepsLocal: [
      'Stir the oats, milk, tahini, chia and chopped dates together in a jar.',
      'Drizzle over the honey.',
      'Refrigerate overnight. Keeps three days, so make the batch at once.',
    ],
  },
  {
    id: 'ae-masala-omelette',
    name: 'Masala omelette',
    en: 'Masala omelette',
    slots: ['breakfast'],
    minutes: 10,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-eggs', g: 180 },
      { id: 'ae-tomato', g: 90 },
      { id: 'ae-onion', g: 40, fixed: true },
      { id: 'ae-coriander', g: 5, fixed: true },
      { id: 'ae-spices', g: 2, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
    ],
    steps: [
      'Beat the eggs with the finely chopped onion, tomato, coriander and spices.',
      'Pour into a hot, oiled pan and cook over a medium heat until just set, folding once.',
    ],
    stepsLocal: [
      'Beat the eggs with the finely chopped onion, tomato, coriander and spices.',
      'Pour into a hot, oiled pan and cook over a medium heat until just set, folding once.',
    ],
  },
  {
    id: 'ae-fruit-labneh-bowl',
    name: 'Fruit and labneh bowl',
    en: 'Fruit and labneh bowl',
    slots: ['breakfast', 'snack'],
    minutes: 5,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-labneh', g: 200 },
      { id: 'ae-banana', g: 100 },
      { id: 'ae-dates', g: 20 },
      { id: 'ae-almonds', g: 15 },
      { id: 'ae-honey', g: 10, fixed: true },
    ],
    steps: [
      'Spoon the labneh into a bowl.',
      'Top with the sliced banana, chopped dates and almonds.',
      'Finish with a drizzle of honey.',
    ],
    stepsLocal: [
      'Spoon the labneh into a bowl.',
      'Top with the sliced banana, chopped dates and almonds.',
      'Finish with a drizzle of honey.',
    ],
  },
  {
    id: 'ae-halloumi-veg-breakfast-plate',
    name: 'Halloumi and vegetable breakfast plate',
    en: 'Halloumi and vegetable breakfast plate',
    slots: ['breakfast'],
    minutes: 12,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-halloumi', g: 100 },
      { id: 'ae-flatbread', g: 70 },
      { id: 'ae-tomato', g: 100 },
      { id: 'ae-cucumber', g: 100 },
      { id: 'ae-zaatar', g: 4, fixed: true },
      { id: 'ae-olive-oil', g: 8, fixed: true },
    ],
    steps: [
      'Slice and grill the halloumi in a dry pan until it colours on both sides.',
      "Warm the flatbread and drizzle the oil and za'atar over it.",
      'Serve with the sliced tomato and cucumber.',
    ],
    stepsLocal: [
      'Slice and grill the halloumi in a dry pan until it colours on both sides.',
      "Warm the flatbread and drizzle the oil and za'atar over it.",
      'Serve with the sliced tomato and cucumber.',
    ],
  },
  {
    id: 'ae-spinach-feta-eggs',
    name: 'Spinach and feta scrambled eggs',
    en: 'Spinach and feta scrambled eggs',
    slots: ['breakfast'],
    minutes: 10,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-eggs', g: 150 },
      { id: 'ae-baby-spinach', g: 60 },
      { id: 'ae-feta', g: 30 },
      { id: 'ae-onion', g: 30, fixed: true },
      { id: 'ae-olive-oil', g: 8, fixed: true },
      { id: 'ae-spices', g: 1, fixed: true },
    ],
    steps: [
      'Soften the onion in the oil, then wilt the spinach through.',
      'Pour in the beaten eggs and spices and stir over a low heat until just set.',
      'Crumble the feta through at the end.',
    ],
    stepsLocal: [
      'Soften the onion in the oil, then wilt the spinach through.',
      'Pour in the beaten eggs and spices and stir over a low heat until just set.',
      'Crumble the feta through at the end.',
    ],
  },

  // ── Lunch ────────────────────────────────────────────────────────────────
  {
    id: 'ae-chicken-shawarma-bowl',
    name: 'Chicken shawarma bowl',
    en: 'Chicken shawarma bowl',
    slots: ['lunch'],
    minutes: 25,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-chicken-thigh', g: 180 },
      { id: 'ae-basmati-rice', g: 60 },
      { id: 'ae-cucumber', g: 100 },
      { id: 'ae-tomato', g: 100 },
      { id: 'ae-tahini', g: 15, fixed: true },
      { id: 'ae-lemon', g: 10, fixed: true },
      { id: 'ae-garlic', g: 5, fixed: true },
      { id: 'ae-olive-oil', g: 6, fixed: true },
      { id: 'ae-baharat', g: 3, fixed: true },
    ],
    steps: [
      'Boil the rice. Toss the chicken with the oil, garlic and baharat and pan-fry until cooked through, about eight minutes.',
      'Slice the chicken and set it over the rice with the diced cucumber and tomato.',
      'Loosen the tahini with the lemon and a splash of water and drizzle over.',
    ],
    stepsLocal: [
      'Boil the rice. Toss the chicken with the oil, garlic and baharat and pan-fry until cooked through, about eight minutes.',
      'Slice the chicken and set it over the rice with the diced cucumber and tomato.',
      'Loosen the tahini with the lemon and a splash of water and drizzle over.',
    ],
  },
  {
    id: 'ae-fattoush-halloumi',
    name: 'Fattoush with grilled halloumi',
    en: 'Fattoush with grilled halloumi',
    slots: ['lunch'],
    minutes: 15,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-halloumi', g: 100 },
      { id: 'ae-flatbread', g: 40 },
      { id: 'ae-cucumber', g: 120 },
      { id: 'ae-cherry-tomatoes', g: 100 },
      { id: 'ae-red-onion', g: 40 },
      { id: 'ae-parsley', g: 10, fixed: true },
      { id: 'ae-mint', g: 5, fixed: true },
      { id: 'ae-sumac', g: 3, fixed: true },
      { id: 'ae-lemon', g: 10, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
    ],
    steps: [
      'Toast or grill the flatbread until crisp, then break it into pieces.',
      'Slice and grill the halloumi in a dry pan until it colours.',
      'Toss the cucumber, tomatoes, onion, parsley and mint with the oil, lemon and sumac, then top with the bread and halloumi.',
    ],
    stepsLocal: [
      'Toast or grill the flatbread until crisp, then break it into pieces.',
      'Slice and grill the halloumi in a dry pan until it colours.',
      'Toss the cucumber, tomatoes, onion, parsley and mint with the oil, lemon and sumac, then top with the bread and halloumi.',
    ],
  },
  {
    id: 'ae-tabbouleh-chickpeas',
    name: 'Tabbouleh with chickpeas',
    en: 'Tabbouleh with chickpeas',
    slots: ['lunch'],
    minutes: 20,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-bulgur', g: 60 },
      { id: 'ae-parsley', g: 60 },
      { id: 'ae-mint', g: 15 },
      { id: 'ae-tomato', g: 100 },
      { id: 'ae-chickpeas-tinned', g: 150 },
      { id: 'ae-lemon', g: 15, fixed: true },
      { id: 'ae-olive-oil', g: 12, fixed: true },
    ],
    steps: [
      'Soak the bulgur in hot water for fifteen minutes, then drain well.',
      'Finely chop the parsley, mint and tomato and stir them through with the drained chickpeas.',
      'Dress with the oil and lemon just before serving.',
    ],
    stepsLocal: [
      'Soak the bulgur in hot water for fifteen minutes, then drain well.',
      'Finely chop the parsley, mint and tomato and stir them through with the drained chickpeas.',
      'Dress with the oil and lemon just before serving.',
    ],
  },
  {
    id: 'ae-lentil-shorba',
    name: 'Lentil shorba',
    en: 'Lentil shorba',
    slots: ['lunch'],
    minutes: 30,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-red-lentils', g: 100 },
      { id: 'ae-carrots', g: 80 },
      { id: 'ae-onion', g: 60, fixed: true },
      { id: 'ae-garlic', g: 5, fixed: true },
      { id: 'ae-cumin', g: 2, fixed: true },
      { id: 'ae-stock-cubes', g: 5, fixed: true },
      { id: 'ae-olive-oil', g: 8, fixed: true },
      { id: 'ae-lemon', g: 5, fixed: true },
    ],
    steps: [
      'Soften the onion, carrot and garlic in the oil.',
      'Add the lentils, cumin, stock cube and water to cover generously. Simmer twenty minutes until the lentils collapse.',
      'Blend smooth if you like, and finish with a squeeze of lemon. Freezes well.',
    ],
    stepsLocal: [
      'Soften the onion, carrot and garlic in the oil.',
      'Add the lentils, cumin, stock cube and water to cover generously. Simmer twenty minutes until the lentils collapse.',
      'Blend smooth if you like, and finish with a squeeze of lemon. Freezes well.',
    ],
  },
  {
    id: 'ae-tuna-freekeh-salad',
    name: 'Tuna and freekeh salad',
    en: 'Tuna and freekeh salad',
    slots: ['lunch'],
    minutes: 20,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-canned-tuna', g: 140 },
      { id: 'ae-freekeh', g: 60 },
      { id: 'ae-cucumber', g: 100 },
      { id: 'ae-cherry-tomatoes', g: 100 },
      { id: 'ae-red-onion', g: 30 },
      { id: 'ae-lemon', g: 10, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
      { id: 'ae-parsley', g: 10, fixed: true },
    ],
    steps: [
      'Boil the freekeh until tender, about fifteen minutes, and drain.',
      'Halve the tomatoes and dice the cucumber and onion.',
      'Toss everything with the drained tuna, oil, lemon and parsley.',
    ],
    stepsLocal: [
      'Boil the freekeh until tender, about fifteen minutes, and drain.',
      'Halve the tomatoes and dice the cucumber and onion.',
      'Toss everything with the drained tuna, oil, lemon and parsley.',
    ],
  },
  {
    id: 'ae-falafel-hummus-plate',
    name: 'Falafel plate with hummus',
    en: 'Falafel plate with hummus',
    slots: ['lunch'],
    minutes: 30,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-dried-chickpeas', g: 90 },
      { id: 'ae-garlic', g: 5, fixed: true },
      { id: 'ae-coriander', g: 10, fixed: true },
      { id: 'ae-cumin', g: 3, fixed: true },
      { id: 'ae-spices', g: 2, fixed: true },
      { id: 'ae-olive-oil', g: 12, fixed: true },
      { id: 'ae-hummus', g: 80 },
      { id: 'ae-tomato', g: 80 },
      { id: 'ae-cucumber', g: 80 },
      { id: 'ae-lemon', g: 5, fixed: true },
    ],
    steps: [
      'Soak the dried chickpeas overnight, then blitz them with the garlic, coriander, cumin and spices to a coarse paste.',
      'Shape into patties and pan-fry in the oil until deep golden, about four minutes a side.',
      'Serve with the hummus, sliced tomato, cucumber and a squeeze of lemon.',
    ],
    stepsLocal: [
      'Soak the dried chickpeas overnight, then blitz them with the garlic, coriander, cumin and spices to a coarse paste.',
      'Shape into patties and pan-fry in the oil until deep golden, about four minutes a side.',
      'Serve with the hummus, sliced tomato, cucumber and a squeeze of lemon.',
    ],
  },
  {
    id: 'ae-machboos-chicken',
    name: 'Machboos with chicken',
    en: 'Machboos with chicken',
    slots: ['lunch'],
    minutes: 45,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-chicken-thigh', g: 180 },
      { id: 'ae-basmati-rice', g: 80 },
      { id: 'ae-onion', g: 60, fixed: true },
      { id: 'ae-tomato-puree', g: 20, fixed: true },
      { id: 'ae-baharat', g: 4, fixed: true },
      { id: 'ae-garlic', g: 5, fixed: true },
      { id: 'ae-olive-oil', g: 8, fixed: true },
      { id: 'ae-lemon', g: 5, fixed: true },
    ],
    steps: [
      'Brown the chicken in the oil, then set it aside and soften the onion and garlic in the same pot.',
      'Stir in the purée and baharat, cook a minute, then return the chicken with the rice and double its volume in water.',
      'Cover and simmer twenty minutes without lifting the lid. Finish with a squeeze of lemon.',
    ],
    stepsLocal: [
      'Brown the chicken in the oil, then set it aside and soften the onion and garlic in the same pot.',
      'Stir in the purée and baharat, cook a minute, then return the chicken with the rice and double its volume in water.',
      'Cover and simmer twenty minutes without lifting the lid. Finish with a squeeze of lemon.',
    ],
  },
  {
    id: 'ae-turkey-veg-wrap',
    name: 'Turkey and vegetable wrap',
    en: 'Turkey and vegetable wrap',
    slots: ['lunch'],
    minutes: 15,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-tortilla', g: 80 },
      { id: 'ae-turkey-breast', g: 130 },
      { id: 'ae-cucumber', g: 60 },
      { id: 'ae-tomato', g: 60 },
      { id: 'ae-labneh', g: 40 },
      { id: 'ae-olive-oil', g: 5, fixed: true },
      { id: 'ae-zaatar', g: 2, fixed: true },
    ],
    steps: [
      'Season and pan-fry the turkey in the oil, then slice it.',
      'Warm the tortilla, spread the labneh and sprinkle the za\'atar.',
      'Fill with the turkey, cucumber and tomato and roll tightly.',
    ],
    stepsLocal: [
      'Season and pan-fry the turkey in the oil, then slice it.',
      'Warm the tortilla, spread the labneh and sprinkle the za\'atar.',
      'Fill with the turkey, cucumber and tomato and roll tightly.',
    ],
  },
  {
    id: 'ae-halloumi-chickpea-salad',
    name: 'Grilled halloumi and chickpea salad',
    en: 'Grilled halloumi and chickpea salad',
    slots: ['lunch'],
    minutes: 15,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-halloumi', g: 90 },
      { id: 'ae-chickpeas-tinned', g: 150 },
      { id: 'ae-cucumber', g: 100 },
      { id: 'ae-cherry-tomatoes', g: 100 },
      { id: 'ae-red-onion', g: 30 },
      { id: 'ae-olive-oil', g: 10, fixed: true },
      { id: 'ae-lemon', g: 10, fixed: true },
      { id: 'ae-sumac', g: 2, fixed: true },
    ],
    steps: [
      'Slice and grill the halloumi in a dry pan until it colours on both sides.',
      'Toss the drained chickpeas, cucumber, tomatoes and onion with the oil, lemon and sumac.',
      'Lay the halloumi on top and serve warm.',
    ],
    stepsLocal: [
      'Slice and grill the halloumi in a dry pan until it colours on both sides.',
      'Toss the drained chickpeas, cucumber, tomatoes and onion with the oil, lemon and sumac.',
      'Lay the halloumi on top and serve warm.',
    ],
  },

  // ── Dinner ───────────────────────────────────────────────────────────────
  {
    id: 'ae-shish-tawook',
    name: 'Shish tawook',
    en: 'Shish tawook',
    slots: ['dinner'],
    minutes: 30,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-chicken-breast', g: 200 },
      { id: 'ae-basmati-rice', g: 70 },
      { id: 'ae-bell-pepper', g: 100 },
      { id: 'ae-onion', g: 50, fixed: true },
      { id: 'ae-lemon', g: 15, fixed: true },
      { id: 'ae-garlic', g: 6, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
      { id: 'ae-baharat', g: 4, fixed: true },
    ],
    steps: [
      'Cube the chicken and marinate in the oil, lemon, garlic and baharat for at least twenty minutes.',
      'Boil the rice. Thread the chicken and pepper onto skewers, alternating with the onion.',
      'Grill eight to ten minutes, turning, until charred and cooked through.',
    ],
    stepsLocal: [
      'Cube the chicken and marinate in the oil, lemon, garlic and baharat for at least twenty minutes.',
      'Boil the rice. Thread the chicken and pepper onto skewers, alternating with the onion.',
      'Grill eight to ten minutes, turning, until charred and cooked through.',
    ],
  },
  {
    id: 'ae-grilled-hammour-rice',
    name: 'Grilled hammour with rice',
    en: 'Grilled hammour with rice',
    slots: ['dinner'],
    minutes: 25,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-hammour-fillet', g: 200 },
      { id: 'ae-basmati-rice', g: 70 },
      { id: 'ae-courgette', g: 100 },
      { id: 'ae-lemon', g: 15, fixed: true },
      { id: 'ae-garlic', g: 5, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
      { id: 'ae-spices', g: 2, fixed: true },
    ],
    steps: [
      'Boil the rice. Slice the courgette and pan-fry it in a little of the oil until golden.',
      'Rub the fish with the remaining oil, garlic and spices.',
      'Pan-fry or grill the fish four minutes a side and finish with the lemon.',
    ],
    stepsLocal: [
      'Boil the rice. Slice the courgette and pan-fry it in a little of the oil until golden.',
      'Rub the fish with the remaining oil, garlic and spices.',
      'Pan-fry or grill the fish four minutes a side and finish with the lemon.',
    ],
  },
  {
    id: 'ae-kabsa-chicken',
    name: 'Kabsa with chicken',
    en: 'Kabsa with chicken',
    slots: ['dinner'],
    minutes: 45,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-chicken-thigh', g: 180 },
      { id: 'ae-basmati-rice', g: 75 },
      { id: 'ae-onion', g: 70, fixed: true },
      { id: 'ae-carrots', g: 50 },
      { id: 'ae-tomato-puree', g: 20, fixed: true },
      { id: 'ae-baharat', g: 5, fixed: true },
      { id: 'ae-garlic', g: 6, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
    ],
    steps: [
      'Brown the chicken in the oil, then set it aside and soften the onion, carrot and garlic in the same pot.',
      'Stir in the purée and baharat, cook a minute, then return the chicken with the rice and double its volume in water.',
      'Cover and simmer twenty-five minutes without lifting the lid, then rest five minutes before serving.',
    ],
    stepsLocal: [
      'Brown the chicken in the oil, then set it aside and soften the onion, carrot and garlic in the same pot.',
      'Stir in the purée and baharat, cook a minute, then return the chicken with the rice and double its volume in water.',
      'Cover and simmer twenty-five minutes without lifting the lid, then rest five minutes before serving.',
    ],
  },
  {
    id: 'ae-beef-kofta-tahini',
    name: 'Beef kofta with tahini sauce',
    en: 'Beef kofta with tahini sauce',
    slots: ['dinner'],
    minutes: 25,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-lean-beef-mince', g: 180 },
      { id: 'ae-onion', g: 50, fixed: true },
      { id: 'ae-parsley', g: 10, fixed: true },
      { id: 'ae-garlic', g: 6, fixed: true },
      { id: 'ae-spices', g: 3, fixed: true },
      { id: 'ae-tahini', g: 20, fixed: true },
      { id: 'ae-lemon', g: 10, fixed: true },
      { id: 'ae-cucumber', g: 100 },
      { id: 'ae-tomato', g: 100 },
    ],
    steps: [
      'Work the mince with the grated onion, parsley, half the garlic and the spices, then shape into fingers.',
      'Grill or pan-fry eight minutes, turning.',
      'Loosen the tahini with the lemon, remaining garlic and a splash of water, and serve alongside with the sliced cucumber and tomato.',
    ],
    stepsLocal: [
      'Work the mince with the grated onion, parsley, half the garlic and the spices, then shape into fingers.',
      'Grill or pan-fry eight minutes, turning.',
      'Loosen the tahini with the lemon, remaining garlic and a splash of water, and serve alongside with the sliced cucumber and tomato.',
    ],
  },
  {
    id: 'ae-chicken-biryani',
    name: 'Chicken biryani',
    en: 'Chicken biryani',
    slots: ['dinner'],
    minutes: 50,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-chicken-thigh', g: 180 },
      { id: 'ae-basmati-rice', g: 75 },
      { id: 'ae-onion', g: 60, fixed: true },
      { id: 'ae-carrots', g: 40 },
      { id: 'ae-greek-yoghurt', g: 40 },
      { id: 'ae-spices', g: 5, fixed: true },
      { id: 'ae-garlic', g: 5, fixed: true },
      { id: 'ae-ginger', g: 5, fixed: true },
      { id: 'ae-olive-oil', g: 8, fixed: true },
    ],
    steps: [
      'Marinate the chicken in the yoghurt, garlic, ginger and half the spices for twenty minutes.',
      'Fry the onion in the oil until deep golden and set half aside for the top.',
      'Layer the marinated chicken, rice, carrot and remaining spices in a pot with the onion, add water to just cover, cover and simmer twenty-five minutes.',
    ],
    stepsLocal: [
      'Marinate the chicken in the yoghurt, garlic, ginger and half the spices for twenty minutes.',
      'Fry the onion in the oil until deep golden and set half aside for the top.',
      'Layer the marinated chicken, rice, carrot and remaining spices in a pot with the onion, add water to just cover, cover and simmer twenty-five minutes.',
    ],
  },
  {
    id: 'ae-prawn-masala',
    name: 'Prawn masala',
    en: 'Prawn masala',
    slots: ['dinner'],
    minutes: 25,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-shrimp', g: 180 },
      { id: 'ae-tomato', g: 150 },
      { id: 'ae-onion', g: 60, fixed: true },
      { id: 'ae-garlic', g: 6, fixed: true },
      { id: 'ae-ginger', g: 6, fixed: true },
      { id: 'ae-spices', g: 4, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
      { id: 'ae-basmati-rice', g: 70 },
    ],
    steps: [
      'Boil the rice. Soften the onion, garlic and ginger in the oil.',
      'Add the chopped tomato and spices and simmer ten minutes until it thickens.',
      'Add the shrimp and cook three to four minutes until just pink. Serve over the rice.',
    ],
    stepsLocal: [
      'Boil the rice. Soften the onion, garlic and ginger in the oil.',
      'Add the chopped tomato and spices and simmer ten minutes until it thickens.',
      'Add the shrimp and cook three to four minutes until just pink. Serve over the rice.',
    ],
  },
  {
    id: 'ae-harissa-salmon-bulgur',
    name: 'Harissa salmon with bulgur',
    en: 'Harissa salmon with bulgur',
    slots: ['dinner'],
    minutes: 25,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-salmon-fillet', g: 180 },
      { id: 'ae-bulgur', g: 70 },
      { id: 'ae-baby-spinach', g: 60 },
      { id: 'ae-harissa', g: 10, fixed: true },
      { id: 'ae-lemon', g: 10, fixed: true },
      { id: 'ae-olive-oil', g: 6, fixed: true },
    ],
    steps: [
      'Boil the bulgur until tender and drain.',
      'Rub the salmon with the harissa and pan-fry or grill four minutes a side.',
      'Wilt the spinach in the pan, stir it through the bulgur with the oil and lemon, and top with the salmon.',
    ],
    stepsLocal: [
      'Boil the bulgur until tender and drain.',
      'Rub the salmon with the harissa and pan-fry or grill four minutes a side.',
      'Wilt the spinach in the pan, stir it through the bulgur with the oil and lemon, and top with the salmon.',
    ],
  },
  {
    id: 'ae-mujadara',
    name: 'Mujadara',
    en: 'Mujadara',
    slots: ['dinner'],
    minutes: 40,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-red-lentils', g: 100 },
      { id: 'ae-basmati-rice', g: 50 },
      { id: 'ae-onion', g: 150, fixed: true },
      { id: 'ae-cumin', g: 3, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
    ],
    steps: [
      'Fry the sliced onion in the oil over a low heat until deeply caramelised, about twenty minutes. Set half aside for the top.',
      'Cook the lentils in plenty of water for ten minutes, then add the rice and cumin and simmer until both are tender.',
      'Stir most of the onion through and scatter the rest on top.',
    ],
    stepsLocal: [
      'Fry the sliced onion in the oil over a low heat until deeply caramelised, about twenty minutes. Set half aside for the top.',
      'Cook the lentils in plenty of water for ten minutes, then add the rice and cumin and simmer until both are tender.',
      'Stir most of the onion through and scatter the rest on top.',
    ],
  },
  {
    id: 'ae-grilled-cod-salad',
    name: 'Grilled cod with salad',
    en: 'Grilled cod with salad',
    slots: ['dinner'],
    minutes: 30,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-cod-fillet', g: 200 },
      { id: 'ae-potatoes', g: 200 },
      { id: 'ae-cherry-tomatoes', g: 100 },
      { id: 'ae-cucumber', g: 80 },
      { id: 'ae-lemon', g: 15, fixed: true },
      { id: 'ae-olive-oil', g: 10, fixed: true },
      { id: 'ae-garlic', g: 5, fixed: true },
      { id: 'ae-spices', g: 2, fixed: true },
    ],
    steps: [
      'Boil the potatoes until tender, then crush them roughly with a little of the oil.',
      'Rub the cod with the remaining oil, garlic and spices and grill or pan-fry four minutes a side.',
      'Serve with the halved tomatoes and sliced cucumber, and a squeeze of lemon.',
    ],
    stepsLocal: [
      'Boil the potatoes until tender, then crush them roughly with a little of the oil.',
      'Rub the cod with the remaining oil, garlic and spices and grill or pan-fry four minutes a side.',
      'Serve with the halved tomatoes and sliced cucumber, and a squeeze of lemon.',
    ],
  },

  // ── Snack ────────────────────────────────────────────────────────────────
  {
    id: 'ae-hummus-vegetables',
    name: 'Hummus with vegetables',
    en: 'Hummus with vegetables',
    slots: ['snack'],
    minutes: 3,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-hummus', g: 150 },
      { id: 'ae-cucumber', g: 100 },
      { id: 'ae-carrots', g: 80 },
      { id: 'ae-bell-pepper', g: 60 },
    ],
    steps: ['Cut the vegetables into sticks and serve with the hummus for dipping.'],
    stepsLocal: ['Cut the vegetables into sticks and serve with the hummus for dipping.'],
  },
  {
    id: 'ae-labneh-cucumber',
    name: 'Labneh with cucumber',
    en: 'Labneh with cucumber',
    slots: ['snack'],
    minutes: 3,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-labneh', g: 180 },
      { id: 'ae-cucumber', g: 100 },
      { id: 'ae-olive-oil', g: 5, fixed: true },
      { id: 'ae-zaatar', g: 2, fixed: true },
    ],
    steps: [
      'Spoon the labneh into a bowl and drizzle with the oil.',
      "Scatter the za'atar over and serve with the sliced cucumber.",
    ],
    stepsLocal: [
      'Spoon the labneh into a bowl and drizzle with the oil.',
      "Scatter the za'atar over and serve with the sliced cucumber.",
    ],
  },
  {
    id: 'ae-dates-almonds',
    name: 'Dates with almonds',
    en: 'Dates with almonds',
    slots: ['snack'],
    minutes: 1,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-dates', g: 70 },
      { id: 'ae-almonds', g: 35 },
    ],
    steps: ['Eat the dates and almonds together. Travels without a fridge.'],
    stepsLocal: ['Eat the dates and almonds together. Travels without a fridge.'],
  },
  {
    id: 'ae-roasted-chickpeas',
    name: 'Roasted chickpeas',
    en: 'Roasted chickpeas',
    slots: ['snack'],
    minutes: 25,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-chickpeas-tinned', g: 200 },
      { id: 'ae-olive-oil', g: 8, fixed: true },
      { id: 'ae-cumin', g: 2, fixed: true },
      { id: 'ae-sumac', g: 2, fixed: true },
      { id: 'ae-spices', g: 1, fixed: true },
    ],
    steps: [
      'Pat the drained chickpeas dry and toss with the oil, cumin, sumac and spices.',
      'Roast at 200°C for twenty to twenty-five minutes, shaking the tray halfway, until crisp.',
    ],
    stepsLocal: [
      'Pat the drained chickpeas dry and toss with the oil, cumin, sumac and spices.',
      'Roast at 200°C for twenty to twenty-five minutes, shaking the tray halfway, until crisp.',
    ],
  },
  {
    id: 'ae-yoghurt-pomegranate',
    name: 'Yoghurt with pomegranate molasses',
    en: 'Yoghurt with pomegranate molasses',
    slots: ['snack'],
    minutes: 3,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-greek-yoghurt', g: 200 },
      { id: 'ae-pomegranate-molasses', g: 10, fixed: true },
      { id: 'ae-walnuts', g: 20 },
      { id: 'ae-honey', g: 8, fixed: true },
    ],
    steps: [
      'Spoon the yoghurt into a bowl.',
      'Drizzle with the pomegranate molasses and honey and scatter the walnuts over.',
    ],
    stepsLocal: [
      'Spoon the yoghurt into a bowl.',
      'Drizzle with the pomegranate molasses and honey and scatter the walnuts over.',
    ],
  },
  {
    id: 'ae-boiled-eggs-sumac',
    name: 'Boiled eggs with sumac',
    en: 'Boiled eggs with sumac',
    slots: ['snack'],
    minutes: 12,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-eggs', g: 120 },
      { id: 'ae-sumac', g: 2, fixed: true },
      { id: 'ae-cucumber', g: 100 },
    ],
    steps: [
      'Boil the eggs nine minutes, cool them under the tap and peel.',
      'Sprinkle with the sumac and serve with the sliced cucumber.',
    ],
    stepsLocal: [
      'Boil the eggs nine minutes, cool them under the tap and peel.',
      'Sprinkle with the sumac and serve with the sliced cucumber.',
    ],
  },
  {
    id: 'ae-tahini-protein-bites',
    name: 'Tahini protein bites',
    en: 'Tahini protein bites',
    slots: ['snack'],
    minutes: 10,
    batchFriendly: true,
    ingredients: [
      { id: 'ae-dates', g: 70 },
      { id: 'ae-tahini', g: 12, fixed: true },
      { id: 'ae-whey-protein', g: 10 },
      { id: 'ae-chia-seeds', g: 10 },
    ],
    steps: [
      'Blitz the dates with the tahini, protein powder and chia seeds to a sticky paste.',
      'Roll into small balls and chill for twenty minutes. Keeps five days in the fridge.',
    ],
    stepsLocal: [
      'Blitz the dates with the tahini, protein powder and chia seeds to a sticky paste.',
      'Roll into small balls and chill for twenty minutes. Keeps five days in the fridge.',
    ],
  },
  {
    id: 'ae-turkey-crispbread',
    name: 'Turkey and crispbread snack',
    en: 'Turkey and crispbread snack',
    slots: ['snack'],
    minutes: 5,
    batchFriendly: false,
    ingredients: [
      { id: 'ae-turkey-breast', g: 80 },
      { id: 'ae-crispbread', g: 24 },
      { id: 'ae-cucumber', g: 60 },
      { id: 'ae-cream-cheese', g: 20 },
    ],
    steps: [
      'Season and pan-fry the turkey, then slice it.',
      'Spread the crispbread with the cream cheese and top with the turkey and sliced cucumber.',
    ],
    stepsLocal: [
      'Season and pan-fry the turkey, then slice it.',
      'Spread the crispbread with the cream cheese and top with the turkey and sliced cucumber.',
    ],
  },
];
