import type { Recipe } from '../../types';

/**
 * Croatian recipes. All quantities are per ONE serving; the planner multiplies
 * them to hit your macro targets, so base amounts sit at a normal portion —
 * roughly 400-700 kcal for mains, 150-350 kcal for snacks.
 *
 * `fixed: true` marks aromatics and seasonings that should not grow with the
 * portion. Nobody wants 1.8x the garlic because they are bulking.
 *
 * These are Croatian dishes rewritten around gram-accurate macros rather than
 * translations of the Swedish pool. Where a classic does not survive the
 * rewrite honestly — sarma needs soured cabbage leaves nobody buys by the
 * kilo — it is left out rather than faked.
 *
 * The pool deliberately mirrors the Swedish one's shape (see the slot counts in
 * the region tests). One place it improves on it: Swedish gluten-free plus
 * dairy-free leaves a single breakfast and a single snack, whereas grilled
 * fish, grah and lentil stews make that combination cheap here.
 */
export const HR_RECIPES: Recipe[] = [
  // ── Doručak ──────────────────────────────────────────────────────────────
  {
    id: 'hr-zobena-kasa-banana',
    name: 'Zobena kaša s bananom i orasima',
    en: 'Oat porridge with banana and walnuts',
    slots: ['breakfast'],
    minutes: 8,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-zobene-pahuljice', g: 80 },
      { id: 'hr-mlijeko', g: 250 },
      { id: 'hr-banana', g: 120 },
      { id: 'hr-orasi', g: 15 },
      { id: 'hr-med', g: 10 },
    ],
    steps: [
      'Bring the oats and milk to a simmer, stirring, until thick — about five minutes.',
      'Slice the banana over the top, scatter the walnuts and drizzle the honey.',
    ],
    stepsLocal: [
      'Zobene pahuljice i mlijeko kuhajte uz miješanje dok se ne zgusne, oko pet minuta.',
      'Odozgo narežite bananu, pospite orasima i prelijte medom.',
    ],
  },
  {
    id: 'hr-nocne-zobene',
    name: 'Noćne zobene pahuljice sa svježim sirom i borovnicama',
    en: 'Overnight oats with quark and blueberries',
    slots: ['breakfast'],
    minutes: 5,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-zobene-pahuljice', g: 80 },
      { id: 'hr-svjezi-sir', g: 200 },
      { id: 'hr-borovnice', g: 100 },
      { id: 'hr-chia', g: 10 },
      { id: 'hr-med', g: 10 },
    ],
    steps: [
      'Stir the oats, quark and chia together in a jar.',
      'Top with the blueberries and honey.',
      'Refrigerate overnight. Keeps three days, so make the batch at once.',
    ],
    stepsLocal: [
      'U staklenci pomiješajte zobene pahuljice, svježi sir i chiu.',
      'Odozgo dodajte borovnice i med.',
      'Ostavite u hladnjaku preko noći. Drži se tri dana, pa pripremite odjednom.',
    ],
  },
  {
    id: 'hr-kajgana-sunka',
    name: 'Kajgana sa šunkom i paprikom',
    en: 'Scrambled eggs with ham and pepper',
    slots: ['breakfast'],
    minutes: 10,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-jaja', g: 180 },
      { id: 'hr-sunka', g: 60 },
      { id: 'hr-paprika', g: 80 },
      { id: 'hr-integralni-kruh', g: 70 },
      { id: 'hr-maslinovo-ulje', g: 5, fixed: true },
      { id: 'hr-zacini', g: 1, fixed: true },
    ],
    steps: [
      'Fry the diced pepper and ham in the oil for two minutes.',
      'Beat the eggs, pour them in and stir over low heat until just set.',
      'Season and serve with the bread.',
    ],
    stepsLocal: [
      'Na ulju dvije minute pržite nakockanu papriku i šunku.',
      'Umutite jaja, ulijte i miješajte na laganoj vatri dok se tek ne stisnu.',
      'Začinite i poslužite s kruhom.',
    ],
  },
  {
    id: 'hr-omlet-tikvica',
    name: 'Omlet s tikvicom i sirom',
    en: 'Courgette and cheese omelette',
    slots: ['breakfast', 'lunch'],
    minutes: 12,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-jaja', g: 180 },
      { id: 'hr-bjelanjci', g: 100 },
      { id: 'hr-tikvica', g: 120 },
      { id: 'hr-ribani-sir', g: 30 },
      { id: 'hr-maslinovo-ulje', g: 5, fixed: true },
      { id: 'hr-zacinsko-bilje', g: 5, fixed: true },
    ],
    steps: [
      'Grate the courgette and squeeze out the water — otherwise the omelette weeps.',
      'Soften it in the oil, pour over the beaten eggs and whites.',
      'Scatter the cheese, fold once the base is set, finish with the herbs.',
    ],
    stepsLocal: [
      'Naribajte tikvicu i iscijedite vodu, inače će omlet pustiti tekućinu.',
      'Kratko je proprživa na ulju, pa prelijte umućenim jajima i bjelanjcima.',
      'Pospite sirom, preklopite kad se dno stisne i završite začinskim biljem.',
    ],
  },
  {
    id: 'hr-jogurt-musli',
    name: 'Grčki jogurt s muslijem i bademima',
    en: 'Greek yoghurt with muesli and almonds',
    slots: ['breakfast', 'snack'],
    minutes: 3,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-grcki-jogurt', g: 250 },
      { id: 'hr-musli', g: 50 },
      { id: 'hr-bademi', g: 20 },
      { id: 'hr-maline', g: 80 },
    ],
    steps: ['Layer the yoghurt, muesli, almonds and raspberries in a bowl.'],
    stepsLocal: ['U zdjelici složite jogurt, musli, bademe i maline.'],
  },
  {
    id: 'hr-tost-avokado-jaje',
    name: 'Tost s avokadom i jajima',
    en: 'Avocado toast with eggs',
    slots: ['breakfast'],
    minutes: 10,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-integralni-kruh', g: 80 },
      { id: 'hr-avokado', g: 80 },
      { id: 'hr-jaja', g: 120 },
      { id: 'hr-limun', g: 5, fixed: true },
      { id: 'hr-zacini', g: 1, fixed: true },
    ],
    steps: [
      'Toast the bread. Mash the avocado with the lemon and a pinch of salt.',
      'Fry or poach the eggs and set them on top.',
    ],
    stepsLocal: [
      'Prepecite kruh. Avokado zgnječite s limunom i prstohvatom soli.',
      'Jaja ispržite ili poširajte i stavite odozgo.',
    ],
  },
  {
    id: 'hr-proteinske-palacinke',
    name: 'Zobene proteinske palačinke',
    en: 'Oat protein pancakes',
    slots: ['breakfast', 'snack'],
    minutes: 15,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-zobene-pahuljice', g: 60 },
      { id: 'hr-protein-prah', g: 30 },
      { id: 'hr-jaja', g: 60 },
      { id: 'hr-protein-mlijeko', g: 120 },
      { id: 'hr-borovnice', g: 80 },
      { id: 'hr-suncokretovo-ulje', g: 4, fixed: true },
    ],
    steps: [
      'Blitz the oats to flour, then blend in the protein, egg and milk.',
      'Fry small pancakes in a lightly oiled pan, two minutes a side.',
      'Serve with the blueberries. The batter keeps a day in the fridge.',
    ],
    stepsLocal: [
      'Zobene pahuljice sameljite u brašno, pa umiksajte protein, jaje i mlijeko.',
      'U nauljenoj tavi pecite manje palačinke, po dvije minute sa svake strane.',
      'Poslužite s borovnicama. Smjesa se drži dan u hladnjaku.',
    ],
  },
  {
    id: 'hr-svjezi-sir-rajcica',
    name: 'Svježi sir s rajčicom i kruhom',
    en: 'Fresh cheese with tomato and bread',
    slots: ['breakfast', 'snack'],
    minutes: 5,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-svjezi-sir', g: 200 },
      { id: 'hr-rajcica', g: 150 },
      { id: 'hr-integralni-kruh', g: 70 },
      { id: 'hr-maslinovo-ulje', g: 5, fixed: true },
      { id: 'hr-zacini', g: 1, fixed: true },
    ],
    steps: [
      'Spoon the cheese onto a plate, slice the tomato beside it.',
      'Salt, pepper, a thread of olive oil, and the bread alongside.',
    ],
    stepsLocal: [
      'Svježi sir stavite na tanjur, uz njega narežite rajčicu.',
      'Posolite, popaprite, prelijte s malo maslinovog ulja i poslužite s kruhom.',
    ],
  },
  {
    id: 'hr-shakshuka-feta',
    name: 'Shakshuka s fetom',
    en: 'Shakshuka with feta',
    slots: ['breakfast', 'lunch'],
    minutes: 20,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-jaja', g: 120 },
      { id: 'hr-pelati', g: 200 },
      { id: 'hr-paprika', g: 100 },
      { id: 'hr-luk', g: 60 },
      { id: 'hr-feta', g: 40 },
      { id: 'hr-integralni-kruh', g: 60 },
      { id: 'hr-maslinovo-ulje', g: 6, fixed: true },
      { id: 'hr-cesnjak', g: 5, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Soften the onion, pepper and garlic in the oil.',
      'Add the tomatoes and spices, simmer ten minutes until it thickens.',
      'Make wells, crack in the eggs, cover until the whites set. Crumble over the feta.',
    ],
    stepsLocal: [
      'Na ulju proprživa luk, papriku i češnjak.',
      'Dodajte pasiranu rajčicu i začine te kuhajte deset minuta da se zgusne.',
      'Napravite udubljenja, razbijte jaja, poklopite dok se bjelanjci ne stisnu. Pospite fetom.',
    ],
  },
  {
    id: 'hr-smoothie-zdjelica',
    name: 'Smoothie zdjelica s malinama',
    en: 'Raspberry smoothie bowl',
    slots: ['breakfast', 'snack'],
    minutes: 5,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-maline', g: 120 },
      { id: 'hr-banana', g: 100 },
      { id: 'hr-grcki-jogurt', g: 150 },
      { id: 'hr-protein-prah', g: 25 },
      { id: 'hr-chia', g: 10 },
    ],
    steps: [
      'Blend the raspberries, banana, yoghurt and protein until thick.',
      'Pour into a bowl and scatter the chia over the top.',
    ],
    stepsLocal: [
      'Izmiksajte maline, bananu, jogurt i protein dok ne bude gusto.',
      'Prelijte u zdjelicu i pospite chia sjemenkama.',
    ],
  },

  // These two exist to cover gluten-free *and* dairy-free at breakfast. Without
  // them that combination has nothing to eat before lunch — every other
  // breakfast here leans on oats, bread, yoghurt or cheese. They are the reason
  // the Croatian pool beats the Swedish one on that filter.
  {
    id: 'hr-kajgana-povrce',
    name: 'Kajgana s povrćem',
    en: 'Scrambled eggs with vegetables',
    slots: ['breakfast'],
    minutes: 12,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-jaja', g: 180 },
      { id: 'hr-paprika', g: 100 },
      { id: 'hr-rajcica', g: 120 },
      { id: 'hr-spinat', g: 40 },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-luk', g: 40, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Soften the onion and pepper in the oil, then add the tomato and cook off its water.',
      'Wilt the spinach through, pour in the beaten eggs and stir over low heat.',
      'Take it off while it still looks slightly underdone — it carries on setting.',
    ],
    stepsLocal: [
      'Na ulju proprživa luk i papriku, dodajte rajčicu i pustite da voda ispari.',
      'Umiješajte špinat da uvene, ulijte umućena jaja i miješajte na laganoj vatri.',
      'Maknite s vatre dok još izgleda malo nedovoljno pečeno — stisnut će se samo.',
    ],
  },
  {
    id: 'hr-batat-jaja-pecnica',
    name: 'Batat s jajima iz pećnice',
    en: 'Baked sweet potato with eggs',
    slots: ['breakfast', 'lunch'],
    minutes: 35,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-batat', g: 250 },
      { id: 'hr-jaja', g: 120 },
      { id: 'hr-paprika', g: 80 },
      { id: 'hr-avokado', g: 60 },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-cesnjak', g: 5, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Cube the sweet potato and pepper, toss with oil and garlic, roast at 200°C for twenty-five minutes.',
      'Make two hollows, crack in the eggs and return for eight minutes.',
      'Sliced avocado over the top. The roast base keeps three days on its own.',
    ],
    stepsLocal: [
      'Batat i papriku nakockajte, pomiješajte s uljem i češnjakom te pecite na 200 °C dvadeset pet minuta.',
      'Napravite dva udubljenja, razbijte jaja i vratite u pećnicu osam minuta.',
      'Odozgo narežite avokado. Pečena podloga sama se drži tri dana.',
    ],
  },

  // ── Ručak i večera ───────────────────────────────────────────────────────
  {
    id: 'hr-piletina-riza-brokula',
    name: 'Piletina s rižom i brokulom',
    en: 'Chicken with rice and broccoli',
    slots: ['lunch', 'dinner'],
    minutes: 25,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-pileca-prsa', g: 180 },
      { id: 'hr-smeda-riza', g: 80 },
      { id: 'hr-brokula', g: 200 },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-cesnjak', g: 5, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Boil the rice. Steam the broccoli for four minutes, keeping it firm.',
      'Season the chicken and pan-fry it six minutes a side, then rest it before slicing.',
      'Finish the broccoli in the pan with the garlic and the chicken juices.',
    ],
    stepsLocal: [
      'Skuhajte rižu. Brokulu kuhajte na pari četiri minute da ostane čvrsta.',
      'Piletinu začinite i pecite po šest minuta sa svake strane, pa ostavite da odmori prije rezanja.',
      'Brokulu dovršite u tavi s češnjakom i sokom od piletine.',
    ],
  },
  {
    id: 'hr-grah-varivo',
    name: 'Grah varivo s mrkvom',
    en: 'Bean stew with carrot',
    slots: ['lunch', 'dinner'],
    minutes: 35,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-crni-grah', g: 250 },
      { id: 'hr-mrkva', g: 120 },
      { id: 'hr-luk', g: 80 },
      { id: 'hr-krumpir', g: 150 },
      { id: 'hr-pelati', g: 150 },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-temeljac', g: 5, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Soften the onion, carrot and garlic in the oil.',
      'Add the potato, tomatoes, stock and water to cover. Simmer twenty minutes.',
      'Stir in the beans and cook ten more. Better on the second day, and it freezes.',
    ],
    stepsLocal: [
      'Na ulju proprživa luk, mrkvu i češnjak.',
      'Dodajte krumpir, pasiranu rajčicu, temeljac i vodu da prekrije. Kuhajte dvadeset minuta.',
      'Umiješajte grah i kuhajte još deset. Drugi dan je bolji, a može i u zamrzivač.',
    ],
  },
  {
    id: 'hr-punjene-paprike',
    name: 'Punjene paprike u umaku od rajčice',
    en: 'Stuffed peppers in tomato sauce',
    slots: ['lunch', 'dinner'],
    minutes: 55,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-paprika', g: 220 },
      { id: 'hr-mjesano-mljeveno', g: 150 },
      { id: 'hr-riza', g: 45 },
      { id: 'hr-luk', g: 60 },
      { id: 'hr-pelati', g: 200 },
      { id: 'hr-jaja', g: 20 },
      { id: 'hr-maslinovo-ulje', g: 6, fixed: true },
      { id: 'hr-cesnjak', g: 5, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Mix the mince, uncooked rice, chopped onion, egg and spices.',
      'Core the peppers and fill them, leaving room — the rice swells.',
      'Stand them in a pot, pour over the tomato and water, simmer covered for forty minutes.',
    ],
    stepsLocal: [
      'Pomiješajte mljeveno meso, nekuhanu rižu, sjeckani luk, jaje i začine.',
      'Paprikama izvadite sredinu i napunite ih, ali ne do vrha — riža nabubri.',
      'Složite ih u lonac, prelijte rajčicom i vodom te kuhajte poklopljeno četrdeset minuta.',
    ],
  },
  {
    id: 'hr-pileci-paprikas',
    name: 'Pileći paprikaš s kuskusom',
    en: 'Chicken paprikash with couscous',
    slots: ['lunch', 'dinner'],
    minutes: 35,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-pileci-zabaci', g: 180 },
      { id: 'hr-kuskus', g: 70 },
      { id: 'hr-paprika', g: 120 },
      { id: 'hr-luk', g: 80 },
      { id: 'hr-pelati', g: 150 },
      { id: 'hr-vrhnje', g: 30 },
      { id: 'hr-suncokretovo-ulje', g: 6, fixed: true },
      { id: 'hr-zacini', g: 3, fixed: true },
    ],
    steps: [
      'Brown the chicken, set it aside, then soften the onion and pepper in the same pan.',
      'Add plenty of paprika off the heat so it does not burn, then the tomatoes and chicken.',
      'Simmer twenty-five minutes. Stir the soured cream in at the end; pour the couscous.',
    ],
    stepsLocal: [
      'Popecite piletinu, izvadite je, pa u istoj tavi proprživa luk i papriku.',
      'Maknite s vatre i dodajte mljevenu papriku da ne zagori, zatim rajčicu i piletinu.',
      'Kuhajte dvadeset pet minuta. Vrhnje umiješajte na kraju; kuskus prelijte vrelom vodom.',
    ],
  },
  {
    id: 'hr-cufte-umak',
    name: 'Ćufte u umaku od rajčice s pireom',
    en: 'Meatballs in tomato sauce with mash',
    slots: ['lunch', 'dinner'],
    minutes: 40,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-junece-mljeveno', g: 160 },
      { id: 'hr-krumpir', g: 250 },
      { id: 'hr-pelati', g: 200 },
      { id: 'hr-luk', g: 60 },
      { id: 'hr-jaja', g: 25 },
      { id: 'hr-mlijeko', g: 50 },
      { id: 'hr-maslinovo-ulje', g: 6, fixed: true },
      { id: 'hr-cesnjak', g: 5, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Mix the mince with the egg, half the onion and the spices; roll into balls.',
      'Brown them, then simmer in the tomato with the garlic for twenty minutes.',
      'Boil and mash the potato with the milk. Both halves reheat well.',
    ],
    stepsLocal: [
      'Mljeveno meso pomiješajte s jajem, pola luka i začinima te oblikujte ćufte.',
      'Popecite ih, pa kuhajte u rajčici s češnjakom dvadeset minuta.',
      'Krumpir skuhajte i izgnječite s mlijekom. Oboje se dobro podgrijava.',
    ],
  },
  {
    id: 'hr-tuna-slanutak-salata',
    name: 'Salata od tune i slanutka',
    en: 'Tuna and chickpea salad',
    slots: ['lunch', 'snack'],
    minutes: 8,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-tuna', g: 140 },
      { id: 'hr-slanutak', g: 150 },
      { id: 'hr-cherry-rajcica', g: 120 },
      { id: 'hr-krastavac', g: 100 },
      { id: 'hr-ljubicasti-luk', g: 40 },
      { id: 'hr-maslinovo-ulje', g: 10, fixed: true },
      { id: 'hr-limun', g: 10, fixed: true },
      { id: 'hr-zacini', g: 1, fixed: true },
    ],
    steps: [
      'Drain the tuna and chickpeas, halve the tomatoes, dice the cucumber and onion.',
      'Dress with the oil, lemon, salt and pepper. Better after ten minutes standing.',
    ],
    stepsLocal: [
      'Ocijedite tunu i slanutak, prepolovite rajčice, nakockajte krastavac i luk.',
      'Začinite uljem, limunom, soli i paprom. Bolja je nakon deset minuta odstajanja.',
    ],
  },
  {
    id: 'hr-wrap-piletina',
    name: 'Wrap s piletinom i povrćem',
    en: 'Chicken and vegetable wrap',
    slots: ['lunch'],
    minutes: 15,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-tortilja', g: 80 },
      { id: 'hr-pileca-prsa', g: 150 },
      { id: 'hr-mijesana-salata', g: 50 },
      { id: 'hr-rajcica', g: 80 },
      { id: 'hr-grcki-jogurt', g: 60 },
      { id: 'hr-maslinovo-ulje', g: 5, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Season and pan-fry the chicken, then slice it.',
      'Warm the tortillas, spread the yoghurt, fill with chicken, salad and tomato, and roll.',
    ],
    stepsLocal: [
      'Piletinu začinite, ispecite u tavi i narežite na trake.',
      'Zagrijte tortilje, namažite jogurtom, napunite piletinom, salatom i rajčicom te zamotajte.',
    ],
  },
  {
    id: 'hr-leca-varivo',
    name: 'Varivo od crvene leće',
    en: 'Red lentil stew',
    slots: ['lunch', 'dinner'],
    minutes: 30,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-crvena-leca', g: 110 },
      { id: 'hr-mrkva', g: 120 },
      { id: 'hr-luk', g: 80 },
      { id: 'hr-pelati', g: 200 },
      { id: 'hr-spinat', g: 60 },
      { id: 'hr-maslinovo-ulje', g: 10, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-dumbir', g: 5, fixed: true },
      { id: 'hr-temeljac', g: 5, fixed: true },
      { id: 'hr-zacini', g: 3, fixed: true },
    ],
    steps: [
      'Soften the onion, carrot, garlic and ginger in the oil.',
      'Add the lentils, tomatoes, stock and water; simmer twenty minutes until they collapse.',
      'Stir the spinach through at the end. Freezes well.',
    ],
    stepsLocal: [
      'Na ulju proprživa luk, mrkvu, češnjak i đumbir.',
      'Dodajte leću, rajčicu, temeljac i vodu; kuhajte dvadeset minuta da se raspadne.',
      'Na kraju umiješajte špinat. Dobro podnosi zamrzavanje.',
    ],
  },
  {
    id: 'hr-tjestenina-tuna',
    name: 'Integralna tjestenina s tunom i rajčicom',
    en: 'Wholegrain pasta with tuna and tomato',
    slots: ['lunch', 'dinner'],
    minutes: 20,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-integralna-tjestenina', g: 90 },
      { id: 'hr-tuna', g: 140 },
      { id: 'hr-pelati', g: 200 },
      { id: 'hr-luk', g: 50 },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Boil the pasta. Soften the onion and garlic in the oil.',
      'Add the tomatoes, simmer ten minutes, then fold in the drained tuna off the heat.',
      'Toss with the pasta and a spoon of its water.',
    ],
    stepsLocal: [
      'Skuhajte tjesteninu. Na ulju proprživa luk i češnjak.',
      'Dodajte rajčicu, kuhajte deset minuta, pa maknite s vatre i umiješajte ocijeđenu tunu.',
      'Pomiješajte s tjesteninom i žlicom vode od kuhanja.',
    ],
  },
  {
    id: 'hr-djuvec-piletina',
    name: 'Đuveč s piletinom',
    en: 'Chicken đuveč',
    slots: ['lunch', 'dinner'],
    minutes: 50,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-pileci-zabaci', g: 170 },
      { id: 'hr-riza', g: 70 },
      { id: 'hr-paprika', g: 120 },
      { id: 'hr-rajcica', g: 120 },
      { id: 'hr-grasak', g: 80 },
      { id: 'hr-luk', g: 70 },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-temeljac', g: 5, fixed: true },
      { id: 'hr-zacini', g: 3, fixed: true },
    ],
    steps: [
      'Brown the chicken in an oven dish, then add the onion, pepper and tomato.',
      'Stir in the rice, peas, stock and twice the rice in water.',
      'Bake at 190°C for thirty-five minutes without stirring, so the top crisps.',
    ],
    stepsLocal: [
      'U vatrostalnoj posudi popecite piletinu, pa dodajte luk, papriku i rajčicu.',
      'Umiješajte rižu, grašak, temeljac i dvostruko vode u odnosu na rižu.',
      'Pecite na 190 °C trideset pet minuta bez miješanja, da se gornji sloj zapeče.',
    ],
  },
  {
    id: 'hr-musaka-krumpir',
    name: 'Musaka s krumpirom',
    en: 'Potato moussaka',
    slots: ['lunch', 'dinner'],
    minutes: 60,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-krumpir', g: 300 },
      { id: 'hr-mjesano-mljeveno', g: 150 },
      { id: 'hr-luk', g: 70 },
      { id: 'hr-jaja', g: 50 },
      { id: 'hr-mlijeko', g: 120 },
      { id: 'hr-ribani-sir', g: 30 },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-zacini', g: 3, fixed: true },
    ],
    steps: [
      'Slice the potato thin. Brown the mince with the onion and season it well.',
      'Layer potato and mince in a dish, finishing with potato.',
      'Beat the eggs with the milk, pour over, scatter the cheese and bake at 200°C for forty minutes.',
    ],
    stepsLocal: [
      'Krumpir narežite na tanke ploške. Mljeveno meso popržite s lukom i dobro začinite.',
      'U posudu slažite red krumpira, red mesa, a na vrh krumpir.',
      'Jaja umutite s mlijekom, prelijte, pospite sirom i pecite na 200 °C četrdeset minuta.',
    ],
  },
  {
    id: 'hr-rizot-kozice',
    name: 'Rižot s kozicama',
    en: 'Prawn risotto',
    slots: ['lunch', 'dinner'],
    minutes: 35,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-riza', g: 85 },
      { id: 'hr-kozice', g: 150 },
      { id: 'hr-luk', g: 60 },
      { id: 'hr-parmezan', g: 15 },
      { id: 'hr-maslinovo-ulje', g: 10, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-limun', g: 10, fixed: true },
      { id: 'hr-temeljac', g: 5, fixed: true },
      { id: 'hr-zacinsko-bilje', g: 5, fixed: true },
    ],
    steps: [
      'Soften the onion in the oil, add the rice and toast it for a minute.',
      'Add hot stock a ladle at a time, stirring, for about eighteen minutes.',
      'Fold in the prawns and garlic for the last three minutes. Finish with lemon and parmesan.',
    ],
    stepsLocal: [
      'Na ulju proprživa luk, dodajte rižu i minutu je pržite.',
      'Dodajte vrući temeljac zaimačom po zaimačom uz miješanje, oko osamnaest minuta.',
      'Zadnje tri minute umiješajte kozice i češnjak. Završite limunom i parmezanom.',
    ],
  },
  {
    id: 'hr-juneci-gulas',
    name: 'Juneći gulaš s krumpirom',
    en: 'Beef goulash with potato',
    slots: ['lunch', 'dinner'],
    minutes: 60,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-junece-mljeveno', g: 160 },
      { id: 'hr-krumpir', g: 250 },
      { id: 'hr-luk', g: 100 },
      { id: 'hr-paprika', g: 100 },
      { id: 'hr-pelati', g: 150 },
      { id: 'hr-suncokretovo-ulje', g: 8, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-temeljac', g: 5, fixed: true },
      { id: 'hr-zacini', g: 4, fixed: true },
    ],
    steps: [
      'Cook the onion slowly until properly soft — this is most of the flavour.',
      'Brown the beef, add paprika off the heat, then tomato, stock and water.',
      'Simmer forty minutes, adding the potato and pepper for the last twenty.',
    ],
    stepsLocal: [
      'Luk dinstajte polako dok ne omekša — u njemu je većina okusa.',
      'Popecite meso, maknite s vatre i dodajte mljevenu papriku, pa rajčicu, temeljac i vodu.',
      'Kuhajte četrdeset minuta, a zadnjih dvadeset dodajte krumpir i papriku.',
    ],
  },
  {
    id: 'hr-curry-slanutak',
    name: 'Curry od slanutka s rižom',
    en: 'Chickpea curry with rice',
    slots: ['lunch', 'dinner'],
    minutes: 30,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-slanutak', g: 250 },
      { id: 'hr-smeda-riza', g: 80 },
      { id: 'hr-kokosovo-mlijeko', g: 120 },
      { id: 'hr-pelati', g: 150 },
      { id: 'hr-luk', g: 80 },
      { id: 'hr-spinat', g: 60 },
      { id: 'hr-suncokretovo-ulje', g: 8, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-dumbir', g: 6, fixed: true },
      { id: 'hr-zacini', g: 4, fixed: true },
    ],
    steps: [
      'Boil the rice. Soften the onion, garlic and ginger, then toast the spices for a minute.',
      'Add the tomatoes and coconut milk, simmer ten minutes, then the drained chickpeas.',
      'Wilt the spinach through at the end.',
    ],
    stepsLocal: [
      'Skuhajte rižu. Proprživa luk, češnjak i đumbir, pa minutu pržite začine.',
      'Dodajte rajčicu i kokosovo mlijeko, kuhajte deset minuta, zatim ocijeđeni slanutak.',
      'Na kraju umiješajte špinat da uvene.',
    ],
  },
  {
    id: 'hr-halloumi-salata',
    name: 'Salata s pečenim halloumijem',
    en: 'Grilled halloumi salad',
    slots: ['lunch'],
    minutes: 15,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-halloumi', g: 100 },
      { id: 'hr-mijesana-salata', g: 60 },
      { id: 'hr-cherry-rajcica', g: 120 },
      { id: 'hr-krastavac', g: 100 },
      { id: 'hr-slanutak', g: 120 },
      { id: 'hr-maslinovo-ulje', g: 10, fixed: true },
      { id: 'hr-limun', g: 10, fixed: true },
      { id: 'hr-zacini', g: 1, fixed: true },
    ],
    steps: [
      'Slice and grill the halloumi in a dry pan until it colours on both sides.',
      'Toss the leaves, tomatoes, cucumber and chickpeas with oil and lemon, and lay it on top.',
    ],
    stepsLocal: [
      'Halloumi narežite i pecite u suhoj tavi dok ne porumeni s obje strane.',
      'Salatu, rajčice, krastavac i slanutak začinite uljem i limunom te odozgo složite sir.',
    ],
  },

  // ── Večera ───────────────────────────────────────────────────────────────
  {
    id: 'hr-oslic-krumpir',
    name: 'Pečeni oslić s krumpirom',
    en: 'Baked hake with potatoes',
    slots: ['dinner'],
    minutes: 35,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-oslic', g: 200 },
      { id: 'hr-krumpir', g: 280 },
      { id: 'hr-cherry-rajcica', g: 100 },
      { id: 'hr-maslinovo-ulje', g: 12, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-limun', g: 15, fixed: true },
      { id: 'hr-zacinsko-bilje', g: 5, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Slice the potatoes, toss with oil and garlic and roast at 200°C for twenty minutes.',
      'Lay the fish and tomatoes on top and roast twelve minutes more.',
      'Lemon and parsley at the table, not before — the fish goes chalky if it sits in acid.',
    ],
    stepsLocal: [
      'Krumpir narežite, pomiješajte s uljem i češnjakom te pecite na 200 °C dvadeset minuta.',
      'Odozgo složite ribu i rajčice pa pecite još dvanaest minuta.',
      'Limun i peršin tek za stolom — riba u kiselini postane brašnjava.',
    ],
  },
  {
    id: 'hr-losos-batat',
    name: 'Losos s batatom i špinatom',
    en: 'Salmon with sweet potato and spinach',
    slots: ['dinner'],
    minutes: 30,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-losos', g: 170 },
      { id: 'hr-batat', g: 250 },
      { id: 'hr-spinat', g: 80 },
      { id: 'hr-maslinovo-ulje', g: 10, fixed: true },
      { id: 'hr-cesnjak', g: 5, fixed: true },
      { id: 'hr-limun', g: 10, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Cube the sweet potato and roast at 200°C for twenty-five minutes.',
      'Pan-fry the salmon skin down for four minutes, one minute on the flesh.',
      'Wilt the spinach with the garlic in the same pan.',
    ],
    stepsLocal: [
      'Batat nakockajte i pecite na 200 °C dvadeset pet minuta.',
      'Losos pecite na koži četiri minute, pa minutu s druge strane.',
      'U istoj tavi s češnjakom kratko prodinstajte špinat.',
    ],
  },
  {
    id: 'hr-cevapi-salata',
    name: 'Ćevapi s lukom i salatom',
    en: 'Ćevapi with onion and salad',
    slots: ['dinner'],
    minutes: 30,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-mjesano-mljeveno', g: 180 },
      { id: 'hr-integralni-kruh', g: 80 },
      { id: 'hr-ljubicasti-luk', g: 60 },
      { id: 'hr-mijesana-salata', g: 60 },
      { id: 'hr-rajcica', g: 100 },
      { id: 'hr-cesnjak', g: 5, fixed: true },
      { id: 'hr-zacini', g: 3, fixed: true },
    ],
    steps: [
      'Work the mince with garlic, salt, pepper and a splash of sparkling water until sticky.',
      'Rest it an hour if you can, shape into fingers and grill eight minutes, turning.',
      'Serve with raw onion, the salad and the bread.',
    ],
    stepsLocal: [
      'Mljeveno meso mijesite s češnjakom, soli, paprom i malo gazirane vode dok ne postane ljepljivo.',
      'Ako stignete, ostavite sat vremena, pa oblikujte ćevape i pecite osam minuta uz okretanje.',
      'Poslužite sa sirovim lukom, salatom i kruhom.',
    ],
  },
  {
    id: 'hr-piletina-zar-spinat',
    name: 'Piletina s žara sa špinatom i krumpirom',
    en: 'Grilled chicken with spinach and potatoes',
    slots: ['dinner'],
    minutes: 30,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-pileca-prsa', g: 190 },
      { id: 'hr-krumpir', g: 250 },
      { id: 'hr-spinat', g: 100 },
      { id: 'hr-maslinovo-ulje', g: 10, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-limun', g: 10, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Boil the potatoes, then crush them roughly with oil and garlic.',
      'Grill the seasoned chicken six minutes a side and rest it.',
      'Wilt the spinach in the pan, finish with lemon.',
    ],
    stepsLocal: [
      'Krumpir skuhajte, pa ga grubo zgnječite s uljem i češnjakom.',
      'Začinjenu piletinu pecite po šest minuta sa svake strane i ostavite da odmori.',
      'U tavi prodinstajte špinat i završite limunom.',
    ],
  },
  {
    id: 'hr-punjene-tikvice',
    name: 'Punjene tikvice s puretinom',
    en: 'Courgettes stuffed with turkey',
    slots: ['dinner'],
    minutes: 45,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-tikvica', g: 250 },
      { id: 'hr-pureca-prsa', g: 150 },
      { id: 'hr-riza', g: 50 },
      { id: 'hr-pelati', g: 150 },
      { id: 'hr-luk', g: 60 },
      { id: 'hr-ribani-sir', g: 25 },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Halve the courgettes and hollow them out; chop what you scooped.',
      'Cook the minced turkey with the onion, courgette flesh and half-cooked rice.',
      'Fill, pour the tomato around, top with cheese, bake at 190°C for twenty-five minutes.',
    ],
    stepsLocal: [
      'Tikvice prepolovite i izdubite; ono što ste izvadili nasjeckajte.',
      'Puretinu popržite s lukom, sredinom tikvice i polukuhanom rižom.',
      'Napunite, uokolo ulijte rajčicu, pospite sirom i pecite na 190 °C dvadeset pet minuta.',
    ],
  },
  {
    id: 'hr-svinjski-file-pire',
    name: 'Svinjski file s pireom i graškom',
    en: 'Pork tenderloin with mash and peas',
    slots: ['dinner'],
    minutes: 35,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-svinjski-file', g: 180 },
      { id: 'hr-krumpir', g: 250 },
      { id: 'hr-grasak', g: 100 },
      { id: 'hr-mlijeko', g: 60 },
      { id: 'hr-senf', g: 8, fixed: true },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Sear the pork all over, then finish in the oven at 180°C for twelve minutes. Rest it.',
      'Mash the boiled potato with the milk; stir the mustard into the pan juices.',
      'Boil the peas for three minutes.',
    ],
    stepsLocal: [
      'File zapecite sa svih strana, pa dovršite u pećnici na 180 °C dvanaest minuta. Ostavite da odmori.',
      'Kuhani krumpir izgnječite s mlijekom; senf umiješajte u sok iz tave.',
      'Grašak kuhajte tri minute.',
    ],
  },
  {
    id: 'hr-tofu-wok',
    name: 'Wok s tofuom i povrćem',
    en: 'Tofu and vegetable stir-fry',
    slots: ['dinner', 'lunch'],
    minutes: 20,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-tofu', g: 180 },
      { id: 'hr-wok-povrce', g: 220 },
      { id: 'hr-smeda-riza', g: 80 },
      { id: 'hr-soja-umak', g: 15, fixed: true },
      { id: 'hr-suncokretovo-ulje', g: 8, fixed: true },
      { id: 'hr-dumbir', g: 6, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-sriracha', g: 5, fixed: true },
    ],
    steps: [
      'Press the tofu dry, cube it and fry hard until it colours on several sides.',
      'Add ginger and garlic, then the vegetables straight from frozen, on the highest heat.',
      'Soy and sriracha at the end. Serve on the rice.',
    ],
    stepsLocal: [
      'Tofu ocijedite, nakockajte i pržite na jakoj vatri dok ne porumeni s više strana.',
      'Dodajte đumbir i češnjak, pa smrznuto povrće izravno iz vrećice, na najjačoj vatri.',
      'Soja i sriracha na kraju. Poslužite uz rižu.',
    ],
  },
  {
    id: 'hr-riba-gradele-povrce',
    name: 'Riba s gradela s pečenim povrćem',
    en: 'Grilled fish with roast vegetables',
    slots: ['dinner'],
    minutes: 30,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-oslic', g: 200 },
      { id: 'hr-tikvica', g: 150 },
      { id: 'hr-paprika', g: 120 },
      { id: 'hr-krumpir', g: 200 },
      { id: 'hr-maslinovo-ulje', g: 12, fixed: true },
      { id: 'hr-cesnjak', g: 5, fixed: true },
      { id: 'hr-limun', g: 15, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Roast the potato, courgette and pepper at 210°C for twenty-five minutes.',
      'Grill the fish four minutes a side on a very hot pan, skin first.',
      'Dress everything with oil, garlic and lemon off the heat.',
    ],
    stepsLocal: [
      'Krumpir, tikvicu i papriku pecite na 210 °C dvadeset pet minuta.',
      'Ribu pecite na vrlo vrućoj tavi po četiri minute, prvo na koži.',
      'Sve prelijte uljem, češnjakom i limunom nakon pečenja.',
    ],
  },
  {
    id: 'hr-pljeskavica-salata',
    name: 'Pljeskavica sa salatom od krastavaca',
    en: 'Pljeskavica with cucumber salad',
    slots: ['dinner'],
    minutes: 25,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-junece-mljeveno', g: 180 },
      { id: 'hr-integralni-kruh', g: 70 },
      { id: 'hr-krastavac', g: 150 },
      { id: 'hr-grcki-jogurt', g: 80 },
      { id: 'hr-ljubicasti-luk', g: 50 },
      { id: 'hr-cesnjak', g: 5, fixed: true },
      { id: 'hr-zacini', g: 3, fixed: true },
    ],
    steps: [
      'Season the mince well and shape one flat patty — thin cooks better than thick.',
      'Grill four minutes a side.',
      'Slice the cucumber and onion, dress with the yoghurt and garlic.',
    ],
    stepsLocal: [
      'Mljeveno meso dobro začinite i oblikujte jednu plosnatu pljeskavicu — tanja se bolje ispeče.',
      'Pecite po četiri minute sa svake strane.',
      'Krastavac i luk narežite te začinite jogurtom i češnjakom.',
    ],
  },
  {
    id: 'hr-piletina-tjestenina-vrhnje',
    name: 'Piletina s tjesteninom i šampinjonima',
    en: 'Chicken pasta with mushrooms',
    slots: ['dinner', 'lunch'],
    minutes: 25,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-pileca-prsa', g: 170 },
      { id: 'hr-integralna-tjestenina', g: 90 },
      { id: 'hr-sampinjoni', g: 150 },
      { id: 'hr-vrhnje', g: 40 },
      { id: 'hr-parmezan', g: 15 },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Boil the pasta. Fry the mushrooms hard and dry before adding any salt.',
      'Add the sliced chicken and garlic, cook through, then the soured cream off the heat.',
      'Toss with the pasta, its water and the parmesan.',
    ],
    stepsLocal: [
      'Skuhajte tjesteninu. Šampinjone pržite na jakoj vatri i posolite ih tek na kraju.',
      'Dodajte narezanu piletinu i češnjak, ispecite, pa maknite s vatre i umiješajte vrhnje.',
      'Pomiješajte s tjesteninom, vodom od kuhanja i parmezanom.',
    ],
  },
  {
    id: 'hr-sojino-bolonjez',
    name: 'Vegetarijanski bolonjez sa sojinim mljevenim',
    en: 'Vegetarian bolognese with soy mince',
    slots: ['dinner', 'lunch'],
    minutes: 30,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-sojino-mljeveno', g: 120 },
      { id: 'hr-integralna-tjestenina', g: 90 },
      { id: 'hr-pelati', g: 250 },
      { id: 'hr-mrkva', g: 80 },
      { id: 'hr-luk', g: 70 },
      { id: 'hr-koncentrat-rajcice', g: 15, fixed: true },
      { id: 'hr-maslinovo-ulje', g: 8, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-zacini', g: 3, fixed: true },
    ],
    steps: [
      'Soften the onion, carrot and garlic slowly in the oil — ten minutes, not three.',
      'Add the purée, cook it out, then the soy mince and tomatoes.',
      'Simmer twenty minutes while the pasta boils.',
    ],
    stepsLocal: [
      'Luk, mrkvu i češnjak dinstajte polako na ulju — deset minuta, ne tri.',
      'Dodajte koncentrat i kratko ga pržite, pa sojino mljeveno i rajčicu.',
      'Kuhajte dvadeset minuta dok se tjestenina kuha.',
    ],
  },
  {
    id: 'hr-skusa-krumpir-salata',
    name: 'Skuša s krumpir salatom',
    en: 'Mackerel with potato salad',
    slots: ['dinner', 'lunch'],
    minutes: 25,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-skusa', g: 190 },
      { id: 'hr-krumpir', g: 280 },
      { id: 'hr-ljubicasti-luk', g: 50 },
      { id: 'hr-maslinovo-ulje', g: 10, fixed: true },
      { id: 'hr-senf', g: 8, fixed: true },
      { id: 'hr-limun', g: 10, fixed: true },
      { id: 'hr-zacinsko-bilje', g: 5, fixed: true },
    ],
    steps: [
      'Boil the potatoes and dress them while still warm — cold potato takes on nothing.',
      'Stir the oil, mustard, lemon and onion through.',
      'Break the mackerel over the top with its sauce.',
    ],
    stepsLocal: [
      'Krumpir skuhajte i začinite dok je još topao — hladan ne prima okus.',
      'Umiješajte ulje, senf, limun i luk.',
      'Odozgo rasporedite skušu zajedno s umakom iz konzerve.',
    ],
  },
  {
    id: 'hr-cvjetaca-zapecena',
    name: 'Zapečena cvjetača sa sirom i jajima',
    en: 'Baked cauliflower cheese',
    slots: ['dinner', 'lunch'],
    minutes: 40,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-cvjetaca', g: 350 },
      { id: 'hr-jaja', g: 120 },
      { id: 'hr-mlijeko', g: 120 },
      { id: 'hr-ribani-sir', g: 50 },
      { id: 'hr-zrnati-sir', g: 100 },
      { id: 'hr-maslinovo-ulje', g: 6, fixed: true },
      { id: 'hr-zacini', g: 2, fixed: true },
    ],
    steps: [
      'Boil the cauliflower florets for five minutes and drain them properly.',
      'Beat the eggs with the milk and cottage cheese, season.',
      'Pour over the cauliflower, top with grated cheese, bake at 190°C for twenty-five minutes.',
    ],
    stepsLocal: [
      'Cvjetaču kuhajte pet minuta i dobro je ocijedite.',
      'Jaja umutite s mlijekom i zrnatim sirom te začinite.',
      'Prelijte cvjetaču, pospite ribanim sirom i pecite na 190 °C dvadeset pet minuta.',
    ],
  },
  {
    id: 'hr-piletina-batat-curry',
    name: 'Piletina s batatom u curryju',
    en: 'Chicken and sweet potato curry',
    slots: ['dinner', 'lunch'],
    minutes: 40,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-pileci-zabaci', g: 180 },
      { id: 'hr-batat', g: 220 },
      { id: 'hr-kokosovo-mlijeko', g: 120 },
      { id: 'hr-pelati', g: 120 },
      { id: 'hr-luk', g: 70 },
      { id: 'hr-spinat', g: 60 },
      { id: 'hr-suncokretovo-ulje', g: 8, fixed: true },
      { id: 'hr-dumbir', g: 6, fixed: true },
      { id: 'hr-cesnjak', g: 6, fixed: true },
      { id: 'hr-zacini', g: 4, fixed: true },
    ],
    steps: [
      'Brown the chicken, set aside. Soften the onion, ginger and garlic, toast the spices.',
      'Add the sweet potato, tomato and coconut milk; simmer twenty minutes.',
      'Return the chicken for the last ten, wilt the spinach in at the end.',
    ],
    stepsLocal: [
      'Popecite piletinu i izvadite je. Proprživa luk, đumbir i češnjak, pa kratko začine.',
      'Dodajte batat, rajčicu i kokosovo mlijeko; kuhajte dvadeset minuta.',
      'Zadnjih deset minuta vratite piletinu, a na kraju umiješajte špinat.',
    ],
  },

  // ── Međuobroci ───────────────────────────────────────────────────────────
  {
    id: 'hr-svjezi-sir-med-orasi',
    name: 'Svježi sir s medom i orasima',
    en: 'Fresh cheese with honey and walnuts',
    slots: ['snack'],
    minutes: 3,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-svjezi-sir', g: 200 },
      { id: 'hr-med', g: 15 },
      { id: 'hr-orasi', g: 20 },
    ],
    steps: ['Spoon the cheese into a bowl, honey over it, walnuts on top.'],
    stepsLocal: ['Svježi sir stavite u zdjelicu, prelijte medom i pospite orasima.'],
  },
  {
    id: 'hr-jogurt-chia',
    name: 'Jogurt s chia sjemenkama i borovnicama',
    en: 'Yoghurt with chia and blueberries',
    slots: ['snack'],
    minutes: 3,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-grcki-jogurt', g: 220 },
      { id: 'hr-chia', g: 15 },
      { id: 'hr-borovnice', g: 100 },
      { id: 'hr-med', g: 8 },
    ],
    steps: ['Stir everything together and leave twenty minutes for the chia to swell.'],
    stepsLocal: ['Sve promiješajte i ostavite dvadesetak minuta da chia nabubri.'],
  },
  {
    id: 'hr-krekeri-kikiriki',
    name: 'Rižini krekeri s maslacem od kikirikija i bananom',
    en: 'Rice cakes with peanut butter and banana',
    slots: ['snack'],
    minutes: 3,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-rizini-krekeri', g: 36 },
      { id: 'hr-maslac-od-kikirikija', g: 30 },
      { id: 'hr-banana', g: 120 },
    ],
    steps: ['Spread the peanut butter on the rice cakes and slice the banana over them.'],
    stepsLocal: ['Krekere namažite maslacem od kikirikija i odozgo narežite bananu.'],
  },
  {
    id: 'hr-protein-shake',
    name: 'Proteinski shake s bananom',
    en: 'Banana protein shake',
    slots: ['snack'],
    minutes: 2,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-protein-prah', g: 30 },
      { id: 'hr-protein-mlijeko', g: 300 },
      { id: 'hr-banana', g: 120 },
    ],
    steps: ['Blend, or shake hard in a bottle if the banana is ripe enough.'],
    stepsLocal: ['Izmiksajte, ili snažno protresite u bočici ako je banana dovoljno zrela.'],
  },
  {
    id: 'hr-bademi-jabuka',
    name: 'Jabuka s bademima',
    en: 'Apple with almonds',
    slots: ['snack'],
    minutes: 2,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-jabuka', g: 180 },
      { id: 'hr-bademi', g: 30 },
    ],
    steps: ['Slice the apple, eat with the almonds. Travels without a fridge.'],
    stepsLocal: ['Narežite jabuku i jedite s bademima. Podnosi put bez hladnjaka.'],
  },
  {
    id: 'hr-kuhana-jaja',
    name: 'Kuhana jaja s krastavcem',
    en: 'Boiled eggs with cucumber',
    slots: ['snack'],
    minutes: 12,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-jaja', g: 180 },
      { id: 'hr-krastavac', g: 150 },
      { id: 'hr-zacini', g: 1, fixed: true },
    ],
    steps: ['Boil the eggs nine minutes, cool them under the tap, peel and salt.'],
    stepsLocal: ['Jaja kuhajte devet minuta, ohladite pod mlazom vode, ogulite i posolite.'],
  },
  {
    id: 'hr-tuna-prepecenac',
    name: 'Prepečenac s tunom',
    en: 'Crispbread with tuna',
    slots: ['snack'],
    minutes: 5,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-prepecenac', g: 36 },
      { id: 'hr-tuna', g: 100 },
      { id: 'hr-grcki-jogurt', g: 40 },
      { id: 'hr-limun', g: 5, fixed: true },
      { id: 'hr-zacini', g: 1, fixed: true },
    ],
    steps: ['Mash the drained tuna with the yoghurt and lemon, spread on the crispbread.'],
    stepsLocal: ['Ocijeđenu tunu izmiješajte s jogurtom i limunom te namažite na prepečenac.'],
  },
  {
    id: 'hr-kakao-puding',
    name: 'Proteinski puding s kakaom',
    en: 'Cocoa protein pudding',
    slots: ['snack'],
    minutes: 5,
    batchFriendly: true,
    ingredients: [
      { id: 'hr-svjezi-sir', g: 200 },
      { id: 'hr-protein-prah', g: 20 },
      { id: 'hr-kakao', g: 8 },
      { id: 'hr-med', g: 10 },
      { id: 'hr-mlijeko', g: 40 },
    ],
    steps: ['Beat everything smooth and chill. Keeps three days.'],
    stepsLocal: ['Sve izmiksajte do glatkog i ohladite. Drži se tri dana.'],
  },
  {
    id: 'hr-zrnati-sir-rajcica',
    name: 'Zrnati sir s cherry rajčicama',
    en: 'Cottage cheese with cherry tomatoes',
    slots: ['snack'],
    minutes: 3,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-zrnati-sir', g: 200 },
      { id: 'hr-cherry-rajcica', g: 120 },
      { id: 'hr-maslinovo-ulje', g: 5, fixed: true },
      { id: 'hr-zacini', g: 1, fixed: true },
    ],
    steps: ['Halve the tomatoes over the cheese, oil, salt and pepper.'],
    stepsLocal: ['Prepolovite rajčice preko sira, dodajte ulje, sol i papar.'],
  },
  {
    id: 'hr-grozdice-orasi',
    name: 'Grožđice s orasima i jogurtom',
    en: 'Raisins with walnuts and yoghurt',
    slots: ['snack'],
    minutes: 2,
    batchFriendly: false,
    ingredients: [
      { id: 'hr-grozdice', g: 30 },
      { id: 'hr-orasi', g: 20 },
      { id: 'hr-grcki-jogurt', g: 180 },
    ],
    steps: ['Stir the raisins and walnuts into the yoghurt.'],
    stepsLocal: ['Grožđice i orahe umiješajte u jogurt.'],
  },
];
